version: '3.8'

services:
  nginx:
    build: services/nginx
    restart: always
    volumes:
      - nginx_logs:/var/log/nginx
    ports:
      - "5010:5010"  # auth_api
    networks:
      - movie_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    expose:
      - 2181
    networks:
      - movie_network

  kafka:
    image: confluentinc/cp-kafka:7.0.0
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    expose:
      - 29092
    ports:
      - "9092:9092"
    networks:
      - movie_network
    depends_on:
      - zookeeper


volumes:
  # Логи для filebeat
  nginx_logs:
  auth_api_logs:
  billing_logs:
  event_to_notification_logs:
  notification_api_logs:
  notification_sender_logs:
  # Статика django
  billing_static_volume:


networks:
  movie_network:
    name: movie_network
    driver: bridge
