version: '3.8'

services:
  auth_api:
    build: .
    volumes:
      - ./src:/app/auth_api
      - ./src/migrations:/app/migrations
    env_file:
      - example.env
    expose:
      - 5000
    ports:
      - "5000:5000"
    networks:
      - external_movie_network
    depends_on:
      - db
      - redis

  db:
    image: postgres:12.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - example.env
    expose:
      - 5432
    ports:
      - "15432:5432"
    networks:
      - external_movie_network

  redis:
    image: redis:6.2.6-alpine
    expose:
      - 6379
    ports:
      - "16379:6379"
    networks:
      - external_movie_network


volumes:
  db_data:


networks:
  external_movie_network:
    name: movie_network
