version: '3.8'

services:
  auth_api:
    build: .
    volumes:
      - ./src/auth_api:/home/app/src/auth_api
      - ./src/auth_api/migrations:/home/app/src/migrations:ro
    env_file:
      - example.env
    entrypoint:
      - /home/app/entrypoint.sh
    expose:
      - 5000
    ports:
      - "5000:5000"
    networks:
      - external_movie_network
    depends_on:
      - db
      - redis

  db:
    image: postgres:12.0-alpine
    env_file:
      - example.env
    expose:
      - 5432
    ports:
      - "15432:5432"
    networks:
      - external_movie_network

  redis:
    image: redis:6.2.6-alpine
    expose:
      - 6379
    ports:
      - "16379:6379"
    networks:
      - external_movie_network


networks:
  external_movie_network:
    name: movie_network
