version: '3.8'

services:
  notification_api:
    build: api
    environment:
      RABBITMQ_USER: admin
      RABBITMQ_PASS: admin
      RABBITMQ_HOST: notification_rabbitmq
      RABBITMQ_PORT: 5672
      REDIS_HOST: notification_redis
      REDIS_PORT: 6379
    volumes:
      - notification_api_logs:/home/app/logs
    expose:
      - 8000
    depends_on:
      notification_rabbitmq:
        condition: service_healthy
      notification_redis:
        condition: service_healthy
    networks:
      - external_movie_network

  notification_sender:
    build: notification_sender
    environment:
      rabbitmq__user: admin
      rabbitmq__password: admin
      rabbitmq__host: notification_rabbitmq
      rabbitmq__port: 5672
      redis__host: notification_redis
      redis__port: 6379
    volumes:
      - notification_sender_logs:/home/app/logs
    depends_on:
      notification_rabbitmq:
        condition: service_healthy
      notification_redis:
        condition: service_healthy
    networks:
      - external_movie_network

  notification_rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 20s
      retries: 100
    expose:
      - 5672  # amqp
      - 15672  # http
    volumes:
      - notification_rabbitmq_data:/var/lib/rabbitmq/
    networks:
      - external_movie_network

  notification_redis:
    image: redis:6.2.6-alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 20s
      retries: 100
    expose:
      - 6379
    ports:
      - "26379:6379"
    networks:
      - external_movie_network

volumes:
  notification_api_logs:
    external: true
  notification_sender_logs:
    external: true
  notification_rabbitmq_data:

networks:
  external_movie_network:
    name: movie_network
