# Переопределение настроек с помощью переменных окружения:
#     rabbitmq__user=bar
#     redis__host=localhost


rabbitmq:
  user: admin
  password: foo  # OVERWRITE ME WITH ENVIRONMENT VARIABLE: rabbitmq__password=bar
  host: rabbitmq
  port: 5672

redis:
  host: redis
  port: 6379

email:
  daily_limit: 10000
  urgent_reserve: 1000  # Резерв для срочных сообщений