# Переопределение настроек с помощью переменных окружения:
#     auth_api__password=bar

project:
  redirect_url: https://tre.one/yookassa/
  admin_email: admin@example.com

notification_api:
  url: http://notification_api:8000/api/v1/send/email

auth_api:
  url: http://localhost/auth/
  login: srv_bills_notif
  password: FdbQJum5RB1kK0YSBnVr

kafka:
  bootstrap_servers: kafka:29092
  auto_offset_reset: earliest
  enable_auto_commit: false
  group_id: event_to_notification_service
  topics:
    - bill
